ZaibBookWeb/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ZaibBook.DataAccess.Infrastructure.IRepository;
using ZaibBook.Models.ViewModel;

namespace ZaibBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        //Interface Injecting DI Like IUnitOfWork . it is used to take access to reache wwwroot folder
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {

            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;

        }

        public IActionResult Index()
        {
            ProductVM vm = new ProductVM();
            vm.Products = _unitOfWork.Product.GetAll();
            return View(vm);
        }

        //GET
        public IActionResult CreateUpdate(Guid? id)
        {
            //Used ViewModel for Tightly Coupled issue
            ProductVM vm = new ProductVM()
            {
                Product = new(),
                //CategoriesList for Dropdown in Product
                Categories = _unitOfWork.Category.GetAll().Select(x =>new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.ID.ToString(),
                    }
                ),
                //WritersList for Dropdown in Product
                Writers = _unitOfWork.Writer.GetAll().Select(x =>

                    new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    }
                )
            };
            if (!id.HasValue)
            {
                return View(vm);
            }
            else
            {
                vm.Product = _unitOfWork.Product.GetT(x => x.Id == id);
                if (vm.Product == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(vm);
                }
            }



        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUpdate(ProductVM vm,IFormFile? file)
        {
            
            if (ModelState.IsValid)
            {
                string fileName = String.Empty;
                if(file !=null)
                {

                    //System.IO.Path.Combine() use to combine to Paths and return string
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "ProductImages");

                    //System.Guid.NewGuid() use to generate New Guid and concate with fileName
                    fileName = Guid.NewGuid().ToString() + "-" + file.FileName;

                    //use to combine uploadDir with fileName and returning filePath string
                    string filePath = Path.Combine(uploadDir, fileName);

                    using (var fileStream=new FileStream(filePath,FileMode.Create))
                    {
                        //Coping file to final location
                        file.CopyTo(fileStream);
                    }
                    //Assigning Path to Product ImageUrl
                    vm.Product.ImageUrl = @"\ProductImages\" + filePath;
                }

                if (vm.Product.Id == Guid.Empty)
                {
                    _unitOfWork.Product.Add(vm.Product);
                    TempData["success"] = "Product Added Successfully";
                }
                else
                {
                    _unitOfWork.Product.Update(vm.Product);
                    TempData["success"] = "Product Updated Successfully";

                }
                _unitOfWork.Save();
                return RedirectToAction("Index");

            }
            else
            {
                return View(vm);
            }


        }


        //GET
        public IActionResult Delete(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }
            var ProductFromDb = _unitOfWork.Product.GetT(x => x.Id == id);
            if (ProductFromDb == null)
            {
                return NotFound();
            }

            return View(ProductFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Guid? id)
        {
            var objProduct = _unitOfWork.Product.GetT(x => x.Id == id);
            if (objProduct == null)
            {
                return NotFound();
            }
            _unitOfWork.Product.Delete(objProduct);
            _unitOfWork.Save();
            TempData["success"] = "Product Deleted Successfully";


            return RedirectToAction("Index");

        }
    }
}

ZaibBookWeb/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Numerics;
using ZaibBook.DataAccess;
using ZaibBook.DataAccess.Infrastructure.IRepository;
using ZaibBook.Models;

namespace ZaibBook.Controllers
{

    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
          
            _unitOfWork = unitOfWork;

        }

        public IActionResult Index()
        {
            IEnumerable<Category> CategoriesList = _unitOfWork.Category.GetAll();
            return View(CategoriesList);
        }
    
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                var isExist = _unitOfWork.Category.GetT(x=>x.Name== obj.Name);
                if (isExist == null)
                {
                    _unitOfWork.Category.Add(obj);
                    _unitOfWork.Save();
                    TempData["success"] = "Category Added Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Name already exist in database";
                    return View(obj);
                }

            }
            else
            {
                return View(obj);
            }

        }

        //GET
        public IActionResult Edit(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }
            var CaregoryFromDb = _unitOfWork.Category.GetT(x=>x.ID == id);
            if (CaregoryFromDb == null)
            {
                return NotFound();
            }

                return View(CaregoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                    _unitOfWork.Category.Update(obj);
                    _unitOfWork.Save();
                    TempData["success"] = "Category Updated Successfully";
                    return RedirectToAction("Index");
            }
            else
            {
                return View(obj);
            }


        }


        //GET
        public IActionResult Delete(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }
            var CaregoryFromDb = _unitOfWork.Category.GetT(x => x.ID == id);
            if (CaregoryFromDb == null)
            {
                return NotFound();
            }

            return View(CaregoryFromDb);
        }

        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Guid ? id)
        {
            var objCategory= _unitOfWork.Category.GetT(x => x.ID == id);
            if (objCategory == null)
            {
                return NotFound();
            }
                _unitOfWork.Category.Delete(objCategory);
                _unitOfWork.Save();
            TempData["success"] = "Category Deleted Successfully";


            return RedirectToAction("Index");

        }
    }
}

ZaibBookWeb/Controllers/WriterController.cs
using Microsoft.AspNetCore.Mvc;
using ZaibBook.DataAccess.Infrastructure.IRepository;
using ZaibBook.DataAccess.Infrastructure.Repository;
using ZaibBook.Models;

namespace ZaibBookWeb.Controllers
{
    public class WriterController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public WriterController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Writer> writerList = _unitOfWork.Writer.GetAll();
            return View(writerList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Writer writer)
        {
            if (ModelState.IsValid)
            {
                var isExist = _unitOfWork.Writer.GetT(x => x.Name == writer.Name);
                if (isExist == null)
                {
                    _unitOfWork.Writer.Add(writer);
                    _unitOfWork.Save();
                    TempData["success"] = "Writer Created Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Name already found in database";
                    return View(writer);
                }
            }
            else
            {
                return View(writer);
            }
        }

        //GET
        public IActionResult Edit(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }
            var data = _unitOfWork.Writer.GetT(x => x.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Writer writer)
        {
            if (ModelState.IsValid)
            {
                var isExist = _unitOfWork.Writer.GetT(x => x.Name == writer.Name);
                if (isExist == null)
                {
                    _unitOfWork.Writer.Update(writer);
                    _unitOfWork.Save();
                    TempData["success"] = "Writer Updated Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Name already found in database";
                    return View(writer);
                }
            }
            else
            {
                return View(writer);
            }
        }


        //GET
        public IActionResult Delete(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }
            var data = _unitOfWork.Writer.GetT(x => x.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Guid? id)
        {

            var result = _unitOfWork.Writer.GetT(x => x.Id == id);

            if (result == null)
            {
                return NotFound();
            }

            _unitOfWork.Writer.Delete(result);
            _unitOfWork.Save();
            TempData["success"] = "Writer Deleted Successfully";
            return RedirectToAction("Index");
        }
    }

}

ZaibBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZaibBookWeb</title>
    <link rel="stylesheet" href="~/css/bootsWatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZaibBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">ZaibBookWeb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">

        <li class="nav-item">
             <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
        </li>
        <li class="nav-item">
             <a class="nav-link" asp-area="Admin" asp-controller="Writer" asp-action="Index">Writer</a>
        </li>
         <li class="nav-item">
             <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
        </li>

                        @*        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>

    </div>
  </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
             <partial name="_Notifications"/>
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted bg-dark text-center">
        <div class="container">
            &copy; 2022 - ZaibBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZaibBookWeb/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>

             <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>
             
            <script type="text/javascript">
                     toastr.success('@TempData["success"]')
            </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
              <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>
                 
                      
                 <script type="text/javascript">
                         toastr.error('@TempData["error"]')
                </script>
}